// UI-10: enum value → i18n key maps, so API enums render as pt-BR labels.
// Keys are listed explicitly (never built from the value), which keeps them
// visible to the i18n completeness spec.
export const TURN_STATUS_LABELS = {
  pending: 'SCANSOLO.LABELS.TURN_STATUSES.PENDING',
  suppressed: 'SCANSOLO.LABELS.TURN_STATUSES.SUPPRESSED',
  succeeded: 'SCANSOLO.LABELS.TURN_STATUSES.SUCCEEDED',
  failed: 'SCANSOLO.LABELS.TURN_STATUSES.FAILED',
};

export const DELIVERY_STATUS_LABELS = {
  sent: 'SCANSOLO.LABELS.DELIVERY_STATUSES.SENT',
  delivered: 'SCANSOLO.LABELS.DELIVERY_STATUSES.DELIVERED',
  read: 'SCANSOLO.LABELS.DELIVERY_STATUSES.READ',
  failed: 'SCANSOLO.LABELS.DELIVERY_STATUSES.FAILED',
  progress: 'SCANSOLO.LABELS.DELIVERY_STATUSES.PROGRESS',
};

export const INDEX_STATUS_LABELS = {
  pending: 'SCANSOLO.LABELS.INDEX_STATUSES.PENDING',
  indexing: 'SCANSOLO.LABELS.INDEX_STATUSES.INDEXING',
  indexed: 'SCANSOLO.LABELS.INDEX_STATUSES.INDEXED',
  failed: 'SCANSOLO.LABELS.INDEX_STATUSES.FAILED',
};

export const ATTEMPT_RESULT_LABELS = {
  scheduled: 'SCANSOLO.LABELS.ATTEMPT_RESULTS.SCHEDULED',
  dispatched: 'SCANSOLO.LABELS.ATTEMPT_RESULTS.DISPATCHED',
  sent: 'SCANSOLO.LABELS.ATTEMPT_RESULTS.SENT',
  skipped: 'SCANSOLO.LABELS.ATTEMPT_RESULTS.SKIPPED',
  failed: 'SCANSOLO.LABELS.ATTEMPT_RESULTS.FAILED',
  cancelled: 'SCANSOLO.LABELS.ATTEMPT_RESULTS.CANCELLED',
};

// Block, deferral, cancellation and proposal failure reasons share one map.
export const REASON_LABELS = {
  template_missing: 'SCANSOLO.LABELS.REASONS.TEMPLATE_MISSING',
  template_rejected: 'SCANSOLO.LABELS.REASONS.TEMPLATE_REJECTED',
  template_paused: 'SCANSOLO.LABELS.REASONS.TEMPLATE_PAUSED',
  template_pending: 'SCANSOLO.LABELS.REASONS.TEMPLATE_PENDING',
  template_disabled: 'SCANSOLO.LABELS.REASONS.TEMPLATE_DISABLED',
  language_unavailable: 'SCANSOLO.LABELS.REASONS.LANGUAGE_UNAVAILABLE',
  params_mismatch: 'SCANSOLO.LABELS.REASONS.PARAMS_MISMATCH',
  scansolo_disabled: 'SCANSOLO.LABELS.REASONS.SCANSOLO_DISABLED',
  config_unavailable: 'SCANSOLO.LABELS.REASONS.CONFIG_UNAVAILABLE',
  inbox_not_allowlisted: 'SCANSOLO.LABELS.REASONS.INBOX_NOT_ALLOWLISTED',
  inbox_has_active_bot: 'SCANSOLO.LABELS.REASONS.INBOX_HAS_ACTIVE_BOT',
  human_controlled: 'SCANSOLO.LABELS.REASONS.HUMAN_CONTROLLED',
  opt_out: 'SCANSOLO.LABELS.REASONS.OPT_OUT',
  conversation_resolved: 'SCANSOLO.LABELS.REASONS.CONVERSATION_RESOLVED',
  timeout: 'SCANSOLO.LABELS.REASONS.TIMEOUT',
  network_error: 'SCANSOLO.LABELS.REASONS.NETWORK_ERROR',
  provider_unavailable: 'SCANSOLO.LABELS.REASONS.PROVIDER_UNAVAILABLE',
  provider_rejected: 'SCANSOLO.LABELS.REASONS.PROVIDER_REJECTED',
  stale_pending: 'SCANSOLO.LABELS.REASONS.STALE_PENDING',
};

export const META_STATUS_LABELS = {
  APPROVED: 'SCANSOLO.LABELS.META_STATUSES.APPROVED',
  REJECTED: 'SCANSOLO.LABELS.META_STATUSES.REJECTED',
  PAUSED: 'SCANSOLO.LABELS.META_STATUSES.PAUSED',
  PENDING: 'SCANSOLO.LABELS.META_STATUSES.PENDING',
  DISABLED: 'SCANSOLO.LABELS.META_STATUSES.DISABLED',
};

export const AVAILABILITY_LABELS = {
  available: 'SCANSOLO.LABELS.AVAILABILITY.AVAILABLE',
  blocked: 'SCANSOLO.LABELS.AVAILABILITY.BLOCKED',
};

export const HANDOFF_TRIGGER_LABELS = {
  explicit: 'SCANSOLO.LABELS.HANDOFF_TRIGGERS.EXPLICIT',
  implicit: 'SCANSOLO.LABELS.HANDOFF_TRIGGERS.IMPLICIT',
  ai_action: 'SCANSOLO.LABELS.HANDOFF_TRIGGERS.AI_ACTION',
};

export const HANDOFF_EVENT_LABELS = {
  'handoff.takeover': 'SCANSOLO.LABELS.HANDOFF_EVENTS.TAKEOVER',
  'handoff.return_to_ai': 'SCANSOLO.LABELS.HANDOFF_EVENTS.RETURN_TO_AI',
  'agent_action.human_handoff': 'SCANSOLO.LABELS.HANDOFF_EVENTS.AI_HANDOFF',
};

export const ERROR_KIND_LABELS = {
  ai_turn: 'SCANSOLO.LABELS.ERROR_KINDS.AI_TURN',
  cadence_attempt: 'SCANSOLO.LABELS.ERROR_KINDS.CADENCE_ATTEMPT',
  make_callback: 'SCANSOLO.LABELS.ERROR_KINDS.MAKE_CALLBACK',
};

export const MAKE_ACTION_LABELS = {
  'proposal.generate': 'SCANSOLO.LABELS.MAKE_ACTIONS.PROPOSAL_GENERATE',
  'proposal.send': 'SCANSOLO.LABELS.MAKE_ACTIONS.PROPOSAL_SEND',
};

export const CALLBACK_REJECTION_LABELS = {
  malformed_json: 'SCANSOLO.LABELS.CALLBACK_REJECTIONS.MALFORMED_JSON',
  schema_invalid: 'SCANSOLO.LABELS.CALLBACK_REJECTIONS.SCHEMA_INVALID',
  unmatched_request: 'SCANSOLO.LABELS.CALLBACK_REJECTIONS.UNMATCHED_REQUEST',
};

// Mirrors ScanSolo::TemplateMapping::PARAM_SOURCES.
export const PARAM_SOURCE_LABELS = {
  contact_name: 'SCANSOLO.LABELS.PARAM_SOURCES.CONTACT_NAME',
  contact_first_name: 'SCANSOLO.LABELS.PARAM_SOURCES.CONTACT_FIRST_NAME',
  agent_name: 'SCANSOLO.LABELS.PARAM_SOURCES.AGENT_NAME',
  stage_label: 'SCANSOLO.LABELS.PARAM_SOURCES.STAGE_LABEL',
  static: 'SCANSOLO.LABELS.PARAM_SOURCES.STATIC',
};

export const AI_ACTION_LABELS = {
  qualification_field: 'SCANSOLO.LABELS.AI_ACTIONS.QUALIFICATION_FIELD',
  stage_transition: 'SCANSOLO.LABELS.AI_ACTIONS.STAGE_TRANSITION',
  private_note: 'SCANSOLO.LABELS.AI_ACTIONS.PRIVATE_NOTE',
  cadence_signal: 'SCANSOLO.LABELS.AI_ACTIONS.CADENCE_SIGNAL',
  human_handoff: 'SCANSOLO.LABELS.AI_ACTIONS.HUMAN_HANDOFF',
  proposal_generate: 'SCANSOLO.LABELS.AI_ACTIONS.PROPOSAL_GENERATE',
};

export const PROVIDER_LABELS = {
  openai: 'SCANSOLO.LABELS.PROVIDERS.OPENAI',
};

export const STAGE_LABELS = {
  novo_lead: 'SCANSOLO.PIPELINE_BOARD.STAGES.NOVO_LEAD',
  em_contato: 'SCANSOLO.PIPELINE_BOARD.STAGES.EM_CONTATO',
  em_qualificacao: 'SCANSOLO.PIPELINE_BOARD.STAGES.EM_QUALIFICACAO',
  qualificado: 'SCANSOLO.PIPELINE_BOARD.STAGES.QUALIFICADO',
  proposta_enviada: 'SCANSOLO.PIPELINE_BOARD.STAGES.PROPOSTA_ENVIADA',
  negociacao: 'SCANSOLO.PIPELINE_BOARD.STAGES.NEGOCIACAO',
  ganho: 'SCANSOLO.PIPELINE_BOARD.STAGES.GANHO',
  perdido: 'SCANSOLO.PIPELINE_BOARD.STAGES.PERDIDO',
};

export const ENROLLMENT_STATUS_LABELS = {
  active: 'SCANSOLO.FOLLOW_UPS.STATUSES.ACTIVE',
  paused: 'SCANSOLO.FOLLOW_UPS.STATUSES.PAUSED',
  cancelled: 'SCANSOLO.FOLLOW_UPS.STATUSES.CANCELLED',
  completed: 'SCANSOLO.FOLLOW_UPS.STATUSES.COMPLETED',
};

export const PROPOSAL_STATUS_LABELS = {
  generating: 'SCANSOLO.PROPOSALS.STATUSES.GENERATING',
  generated: 'SCANSOLO.PROPOSALS.STATUSES.GENERATED',
  approved: 'SCANSOLO.PROPOSALS.STATUSES.APPROVED',
  sent: 'SCANSOLO.PROPOSALS.STATUSES.SENT',
  failed: 'SCANSOLO.PROPOSALS.STATUSES.FAILED',
};

// RF-01 / UI-02: card tag; an empty origin shows no tag.
export const LEAD_SOURCE_TAGS = {
  website: 'SCANSOLO.LABELS.LEAD_SOURCE_TAGS.WEBSITE',
  manual: 'SCANSOLO.LABELS.LEAD_SOURCE_TAGS.MANUAL',
};

// UI-04: an empty origin reads "Não informada".
export const LEAD_SOURCE_LABELS = {
  website: 'SCANSOLO.LABELS.LEAD_SOURCES.WEBSITE',
  manual: 'SCANSOLO.LABELS.LEAD_SOURCES.MANUAL',
  none: 'SCANSOLO.LABELS.LEAD_SOURCES.NONE',
};

// RF-45: display-only mapping of the LeadState field classification.
export const FIELD_STATUS_LABELS = {
  confirmado: 'SCANSOLO.LABELS.FIELD_STATUSES.CONFIRMADO',
  inferido: 'SCANSOLO.LABELS.FIELD_STATUSES.INFERIDO',
  faltante: 'SCANSOLO.LABELS.FIELD_STATUSES.FALTANTE',
};

// RF-33: `generated` (and the historical `approved`) is never shown as sent.
const PROPOSAL_COMMERCIAL_STATUS_LABELS = {
  generating: 'SCANSOLO.LABELS.COMMERCIAL_STATUSES.GENERATING',
  generated: 'SCANSOLO.LABELS.COMMERCIAL_STATUSES.GENERATED',
  approved: 'SCANSOLO.LABELS.COMMERCIAL_STATUSES.GENERATED',
  sent: 'SCANSOLO.LABELS.COMMERCIAL_STATUSES.SENT',
  failed: 'SCANSOLO.LABELS.COMMERCIAL_STATUSES.FAILED',
};

const QUOTE_REQUEST_COMMERCIAL_STATUS_LABELS = {
  awaiting_reply: 'SCANSOLO.LABELS.COMMERCIAL_STATUSES.AWAITING_REPLY',
  correction_requested:
    'SCANSOLO.LABELS.COMMERCIAL_STATUSES.CORRECTION_REQUESTED',
  replied: 'SCANSOLO.LABELS.COMMERCIAL_STATUSES.REPLIED',
};

// UI-02 / UI-04: one quote/proposal label per opportunity; the proposal
// status wins over the quote request status. `null` → no label.
export const commercialStatusKey = (quoteRequestStatus, proposalStatus) =>
  PROPOSAL_COMMERCIAL_STATUS_LABELS[proposalStatus] ||
  QUOTE_REQUEST_COMMERCIAL_STATUS_LABELS[quoteRequestStatus] ||
  null;

// CT-01 / UI-01: 422 reason → message.
export const MANUAL_LEAD_ERROR_LABELS = {
  missing_name: 'SCANSOLO.PIPELINE_BOARD.NEW_LEAD.ERRORS.MISSING_NAME',
  invalid_phone: 'SCANSOLO.PIPELINE_BOARD.NEW_LEAD.ERRORS.INVALID_PHONE',
  invalid_email: 'SCANSOLO.PIPELINE_BOARD.NEW_LEAD.ERRORS.INVALID_EMAIL',
  invalid_owner: 'SCANSOLO.PIPELINE_BOARD.NEW_LEAD.ERRORS.INVALID_OWNER',
  invalid_inbox: 'SCANSOLO.PIPELINE_BOARD.NEW_LEAD.ERRORS.INVALID_INBOX',
  contact_opted_out:
    'SCANSOLO.PIPELINE_BOARD.NEW_LEAD.ERRORS.CONTACT_OPTED_OUT',
  contact_conflict: 'SCANSOLO.PIPELINE_BOARD.NEW_LEAD.ERRORS.CONTACT_CONFLICT',
  opportunity_exists:
    'SCANSOLO.PIPELINE_BOARD.NEW_LEAD.ERRORS.OPPORTUNITY_EXISTS',
};

// CT-12 / UI-07: 422 reason → message.
export const QUOTE_REQUEST_RESEND_ERROR_LABELS = {
  quote_request_closed:
    'SCANSOLO.PIPELINE_BOARD.DETAIL.RESEND_QUOTE_REQUEST.ERRORS.QUOTE_REQUEST_CLOSED',
  quote_request_not_eligible:
    'SCANSOLO.PIPELINE_BOARD.DETAIL.RESEND_QUOTE_REQUEST.ERRORS.QUOTE_REQUEST_NOT_ELIGIBLE',
  quote_inbox_misconfigured:
    'SCANSOLO.PIPELINE_BOARD.DETAIL.RESEND_QUOTE_REQUEST.ERRORS.QUOTE_INBOX_MISCONFIGURED',
};

// RF-08 / UI-04: status of the manual lead's initial template failure.
export const INITIAL_TEMPLATE_FAILURE_STATUS_LABELS = {
  blocked:
    'SCANSOLO.PIPELINE_BOARD.DETAIL.INITIAL_TEMPLATE_FAILURE.STATUSES.BLOCKED',
  failed:
    'SCANSOLO.PIPELINE_BOARD.DETAIL.INITIAL_TEMPLATE_FAILURE.STATUSES.FAILED',
};

// CT-08 / UI-05: 422 reason → message.
export const QUOTE_REPLY_ERROR_LABELS = {
  already_linked: 'SCANSOLO.PROPOSALS.PENDING_REPLIES.ERRORS.ALREADY_LINKED',
  quote_request_closed:
    'SCANSOLO.PROPOSALS.PENDING_REPLIES.ERRORS.QUOTE_REQUEST_CLOSED',
  already_discarded:
    'SCANSOLO.PROPOSALS.PENDING_REPLIES.ERRORS.ALREADY_DISCARDED',
  not_discardable: 'SCANSOLO.PROPOSALS.PENDING_REPLIES.ERRORS.NOT_DISCARDABLE',
  invalid_quote_request_id:
    'SCANSOLO.PROPOSALS.PENDING_REPLIES.ERRORS.INVALID_QUOTE_REQUEST_ID',
};

// Mirrors the ScanSolo::TemplateMapping slots added by this feature.
export const TEMPLATE_SLOT_LABELS = {
  lead_manual_inicial:
    'SCANSOLO.FOLLOW_UPS.TEMPLATES.SLOTS.LEAD_MANUAL_INICIAL',
  proposta_acompanhamento:
    'SCANSOLO.FOLLOW_UPS.TEMPLATES.SLOTS.PROPOSTA_ACOMPANHAMENTO',
};

// Translates a known enum value; free-form values (e.g. a provider error
// message) are shown as they came from the server.
export const enumLabel = (t, labels, value) => {
  if (value === null || value === undefined || value === '') return '';
  // Keys come from the static maps above.
  // eslint-disable-next-line @intlify/vue-i18n/no-dynamic-keys
  return labels[value] ? t(labels[value]) : String(value);
};
