// UI-10: enum value → i18n key maps, so API enums render as pt-BR labels.
// Keys are listed explicitly (never built from the value), which keeps them
// visible to the i18n completeness spec.
export const TURN_STATUS_LABELS = {
  pending: 'SCANSOLO.LABELS.TURN_STATUSES.PENDING',
  suppressed: 'SCANSOLO.LABELS.TURN_STATUSES.SUPPRESSED',
  succeeded: 'SCANSOLO.LABELS.TURN_STATUSES.SUCCEEDED',
  failed: 'SCANSOLO.LABELS.TURN_STATUSES.FAILED',
};

export const DELIVERY_STATUS_LABELS = {
  sent: 'SCANSOLO.LABELS.DELIVERY_STATUSES.SENT',
  delivered: 'SCANSOLO.LABELS.DELIVERY_STATUSES.DELIVERED',
  read: 'SCANSOLO.LABELS.DELIVERY_STATUSES.READ',
  failed: 'SCANSOLO.LABELS.DELIVERY_STATUSES.FAILED',
  progress: 'SCANSOLO.LABELS.DELIVERY_STATUSES.PROGRESS',
};

export const INDEX_STATUS_LABELS = {
  pending: 'SCANSOLO.LABELS.INDEX_STATUSES.PENDING',
  indexing: 'SCANSOLO.LABELS.INDEX_STATUSES.INDEXING',
  indexed: 'SCANSOLO.LABELS.INDEX_STATUSES.INDEXED',
  failed: 'SCANSOLO.LABELS.INDEX_STATUSES.FAILED',
};

export const ATTEMPT_RESULT_LABELS = {
  scheduled: 'SCANSOLO.LABELS.ATTEMPT_RESULTS.SCHEDULED',
  dispatched: 'SCANSOLO.LABELS.ATTEMPT_RESULTS.DISPATCHED',
  sent: 'SCANSOLO.LABELS.ATTEMPT_RESULTS.SENT',
  skipped: 'SCANSOLO.LABELS.ATTEMPT_RESULTS.SKIPPED',
  failed: 'SCANSOLO.LABELS.ATTEMPT_RESULTS.FAILED',
  cancelled: 'SCANSOLO.LABELS.ATTEMPT_RESULTS.CANCELLED',
};

// Block, deferral, cancellation and proposal failure reasons share one map.
export const REASON_LABELS = {
  template_missing: 'SCANSOLO.LABELS.REASONS.TEMPLATE_MISSING',
  template_rejected: 'SCANSOLO.LABELS.REASONS.TEMPLATE_REJECTED',
  template_paused: 'SCANSOLO.LABELS.REASONS.TEMPLATE_PAUSED',
  template_pending: 'SCANSOLO.LABELS.REASONS.TEMPLATE_PENDING',
  template_disabled: 'SCANSOLO.LABELS.REASONS.TEMPLATE_DISABLED',
  language_unavailable: 'SCANSOLO.LABELS.REASONS.LANGUAGE_UNAVAILABLE',
  params_mismatch: 'SCANSOLO.LABELS.REASONS.PARAMS_MISMATCH',
  scansolo_disabled: 'SCANSOLO.LABELS.REASONS.SCANSOLO_DISABLED',
  config_unavailable: 'SCANSOLO.LABELS.REASONS.CONFIG_UNAVAILABLE',
  inbox_not_allowlisted: 'SCANSOLO.LABELS.REASONS.INBOX_NOT_ALLOWLISTED',
  inbox_has_active_bot: 'SCANSOLO.LABELS.REASONS.INBOX_HAS_ACTIVE_BOT',
  human_controlled: 'SCANSOLO.LABELS.REASONS.HUMAN_CONTROLLED',
  opt_out: 'SCANSOLO.LABELS.REASONS.OPT_OUT',
  conversation_resolved: 'SCANSOLO.LABELS.REASONS.CONVERSATION_RESOLVED',
  timeout: 'SCANSOLO.LABELS.REASONS.TIMEOUT',
  network_error: 'SCANSOLO.LABELS.REASONS.NETWORK_ERROR',
  provider_unavailable: 'SCANSOLO.LABELS.REASONS.PROVIDER_UNAVAILABLE',
  provider_rejected: 'SCANSOLO.LABELS.REASONS.PROVIDER_REJECTED',
  stale_pending: 'SCANSOLO.LABELS.REASONS.STALE_PENDING',
};

export const META_STATUS_LABELS = {
  APPROVED: 'SCANSOLO.LABELS.META_STATUSES.APPROVED',
  REJECTED: 'SCANSOLO.LABELS.META_STATUSES.REJECTED',
  PAUSED: 'SCANSOLO.LABELS.META_STATUSES.PAUSED',
  PENDING: 'SCANSOLO.LABELS.META_STATUSES.PENDING',
  DISABLED: 'SCANSOLO.LABELS.META_STATUSES.DISABLED',
};

export const AVAILABILITY_LABELS = {
  available: 'SCANSOLO.LABELS.AVAILABILITY.AVAILABLE',
  blocked: 'SCANSOLO.LABELS.AVAILABILITY.BLOCKED',
};

export const HANDOFF_TRIGGER_LABELS = {
  explicit: 'SCANSOLO.LABELS.HANDOFF_TRIGGERS.EXPLICIT',
  implicit: 'SCANSOLO.LABELS.HANDOFF_TRIGGERS.IMPLICIT',
  ai_action: 'SCANSOLO.LABELS.HANDOFF_TRIGGERS.AI_ACTION',
};

export const HANDOFF_EVENT_LABELS = {
  'handoff.takeover': 'SCANSOLO.LABELS.HANDOFF_EVENTS.TAKEOVER',
  'handoff.return_to_ai': 'SCANSOLO.LABELS.HANDOFF_EVENTS.RETURN_TO_AI',
  'agent_action.human_handoff': 'SCANSOLO.LABELS.HANDOFF_EVENTS.AI_HANDOFF',
};

export const ERROR_KIND_LABELS = {
  ai_turn: 'SCANSOLO.LABELS.ERROR_KINDS.AI_TURN',
  cadence_attempt: 'SCANSOLO.LABELS.ERROR_KINDS.CADENCE_ATTEMPT',
  make_callback: 'SCANSOLO.LABELS.ERROR_KINDS.MAKE_CALLBACK',
};

export const MAKE_ACTION_LABELS = {
  'proposal.generate': 'SCANSOLO.LABELS.MAKE_ACTIONS.PROPOSAL_GENERATE',
  'proposal.send': 'SCANSOLO.LABELS.MAKE_ACTIONS.PROPOSAL_SEND',
};

export const CALLBACK_REJECTION_LABELS = {
  malformed_json: 'SCANSOLO.LABELS.CALLBACK_REJECTIONS.MALFORMED_JSON',
  schema_invalid: 'SCANSOLO.LABELS.CALLBACK_REJECTIONS.SCHEMA_INVALID',
  unmatched_request: 'SCANSOLO.LABELS.CALLBACK_REJECTIONS.UNMATCHED_REQUEST',
};

// Mirrors ScanSolo::TemplateMapping::PARAM_SOURCES.
export const PARAM_SOURCE_LABELS = {
  contact_name: 'SCANSOLO.LABELS.PARAM_SOURCES.CONTACT_NAME',
  contact_first_name: 'SCANSOLO.LABELS.PARAM_SOURCES.CONTACT_FIRST_NAME',
  agent_name: 'SCANSOLO.LABELS.PARAM_SOURCES.AGENT_NAME',
  stage_label: 'SCANSOLO.LABELS.PARAM_SOURCES.STAGE_LABEL',
  static: 'SCANSOLO.LABELS.PARAM_SOURCES.STATIC',
};

export const AI_ACTION_LABELS = {
  qualification_field: 'SCANSOLO.LABELS.AI_ACTIONS.QUALIFICATION_FIELD',
  stage_transition: 'SCANSOLO.LABELS.AI_ACTIONS.STAGE_TRANSITION',
  private_note: 'SCANSOLO.LABELS.AI_ACTIONS.PRIVATE_NOTE',
  cadence_signal: 'SCANSOLO.LABELS.AI_ACTIONS.CADENCE_SIGNAL',
  human_handoff: 'SCANSOLO.LABELS.AI_ACTIONS.HUMAN_HANDOFF',
  proposal_generate: 'SCANSOLO.LABELS.AI_ACTIONS.PROPOSAL_GENERATE',
};

export const PROVIDER_LABELS = {
  openai: 'SCANSOLO.LABELS.PROVIDERS.OPENAI',
};

export const STAGE_LABELS = {
  novo_lead: 'SCANSOLO.PIPELINE_BOARD.STAGES.NOVO_LEAD',
  em_contato: 'SCANSOLO.PIPELINE_BOARD.STAGES.EM_CONTATO',
  em_qualificacao: 'SCANSOLO.PIPELINE_BOARD.STAGES.EM_QUALIFICACAO',
  qualificado: 'SCANSOLO.PIPELINE_BOARD.STAGES.QUALIFICADO',
  proposta_enviada: 'SCANSOLO.PIPELINE_BOARD.STAGES.PROPOSTA_ENVIADA',
  negociacao: 'SCANSOLO.PIPELINE_BOARD.STAGES.NEGOCIACAO',
  ganho: 'SCANSOLO.PIPELINE_BOARD.STAGES.GANHO',
  perdido: 'SCANSOLO.PIPELINE_BOARD.STAGES.PERDIDO',
};

export const ENROLLMENT_STATUS_LABELS = {
  active: 'SCANSOLO.FOLLOW_UPS.STATUSES.ACTIVE',
  paused: 'SCANSOLO.FOLLOW_UPS.STATUSES.PAUSED',
  cancelled: 'SCANSOLO.FOLLOW_UPS.STATUSES.CANCELLED',
  completed: 'SCANSOLO.FOLLOW_UPS.STATUSES.COMPLETED',
};

export const PROPOSAL_STATUS_LABELS = {
  generating: 'SCANSOLO.PROPOSALS.STATUSES.GENERATING',
  generated: 'SCANSOLO.PROPOSALS.STATUSES.GENERATED',
  approved: 'SCANSOLO.PROPOSALS.STATUSES.APPROVED',
  sent: 'SCANSOLO.PROPOSALS.STATUSES.SENT',
  failed: 'SCANSOLO.PROPOSALS.STATUSES.FAILED',
};

// Translates a known enum value; free-form values (e.g. a provider error
// message) are shown as they came from the server.
export const enumLabel = (t, labels, value) => {
  if (value === null || value === undefined || value === '') return '';
  // Keys come from the static maps above.
  // eslint-disable-next-line @intlify/vue-i18n/no-dynamic-keys
  return labels[value] ? t(labels[value]) : String(value);
};
